### PR TITLE
Add setup instructions to create local database

### PR DESCRIPTION
**Pull request by raindogg**
Finish the updated setup instructions by adding steps to create and connect to a local postgres database.

### CODE REVIEW

**Comment by briwagner** [comment]
Looks good, Will! Another option is a docker-compose setup that creates a DB and the admin interface. The official Postgres Docker image has the example using adminer.

**Comment by raindogg** [comment]
Thanks Brian! Doing both at once sounds like a good idea. I'm not too familiar with docker-compose, but if you wanted to write up some steps to include in the readme it might help to give people different options

**Comment by briwagner** [comment]
Will, just added a basic compose file with some instructions alongside yours. I'm sure we could provide more instruction on Docker basics, compose, etc., but maybe see what's needed by those involved before going further.

**Comment by raindogg** [comment]
Looks good, thanks Brian!

**Review by briwagner — APPROVED** [review]

**Pull request merged**
